# Generated by Django 4.1.7 on 2023-03-29 05:09

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=60, null=True)),
                ('details', models.TextField(max_length=200)),
                ('logo', models.ImageField(upload_to='media')),
                ('facebook_url', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True)),
                ('youtube_url', models.CharField(blank=True, max_length=150, null=True)),
                ('pinterest_url', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Blog Info',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '2. Category',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('feature_img', models.ImageField(upload_to='media')),
                ('featured_post', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('seo_title', models.CharField(blank=True, help_text='Enter Optimized SEO Title(max length: 70 chars)', max_length=70, null=True)),
                ('seo_description', models.TextField(blank=True, help_text='Enter Optimized SEO Description(max length: 160 chars)', max_length=160, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=50)),
                ('publish_on', models.DateTimeField(auto_now_add=True)),
                ('modify_on', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': '3. All Posts',
                'ordering': ['-publish_on'],
            },
        ),
    ]
